#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
obj-$(CONFIG_PRIZE_HARDWARE_INFO) += hardware_info/

# Makefile for the board id drivers.
obj-$(CONFIG_PRIZE_BOARD_ID) += board_id/

# prize liuyong, Add SIM card slot detection, 20240103, start
obj-$(CONFIG_PRIZE_SIM_SLOT_CHECK) += sim_slot/
# prize liuyong, Add SIM card slot detection, 20240103, end

# drv added by ocean 20240330 begin
obj-$(CONFIG_CS_NOTIFIER) += cs_notifier/
# drv added by ocean 20240330 end

# pri added for SL005TC-231 20250610 begin
obj-$(CONFIG_CS_USB_BROADCAST) += cs_usb_broadcast/
# pri added for SL005TC-231 20250610 end
